name: Terminal Adapter Test

on:
  # Build master branch only
  push:
    branches:
      - master
  # Build pull requests targeting master branch only
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{matrix.rust}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        backend_features: [crossterm-backend, termion-backend]
        os: [ubuntu-latest, windows-2019, macOS-latest]
        rust: [stable, nightly]
        # Allow failures on nightly, it's just informative
        include:
          - rust: stable
            can-fail: false
          - rust: nightly
            can-fail: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt,clippy
    - name: Toolchain Information
      run: |
        rustc --version
        rustfmt --version
        rustup --version
        cargo --version
    - name: Check Formatting
      if: matrix.rust == 'stable'
      run: cargo fmt --all -- --check
      continue-on-error: ${{ matrix.can-fail }}
    - name: Clippy
      run: cargo clippy -- -D clippy::all
      continue-on-error: ${{ matrix.can-fail }}
      
    - name: Build with feature crosterm-backend
      run: cargo build --no-default-features --features="crossterm-backend"
      continue-on-error: ${{ matrix.can-fail }}            
    - name: Build with feature termion-backend
      if: matrix.os != 'windows-2019'
      run: cargo build --no-default-features --features="termion-backend"
      continue-on-error: ${{ matrix.can-fail }}
      
    - name: Test with feature crosterm-backend
      run: cargo test --no-default-features --features="crossterm-backend"
      continue-on-error: ${{ matrix.can-fail }}            
    - name: Test with feature termion-backend
      if: matrix.os != 'windows-2019'
      run: cargo text --no-default-features --features="termion-backend"
      continue-on-error: ${{ matrix.can-fail }}
    
    - name: Test Packaging
      if: matrix.rust == 'stable'
      run: cargo package
      continue-on-error: ${{ matrix.can-fail }}
